[package]
edition = "2024"
name    = "elf-testkit"
version = "0.1.0"

[dependencies]
qdrant-client = { workspace = true }
sqlx          = { workspace = true }
thiserror     = { workspace = true }
tokio         = { workspace = true }
uuid          = { workspace = true }
