[package]
edition = "2024"
name    = "elf-config"
version = "0.1.0"

[dependencies]
color-eyre = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
toml       = { workspace = true }
