[package]
name = "elf-config"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
