[package]
edition = "2024"
name    = "elf-domain"
version = "0.2.0"

[dependencies]
regex      = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
time       = { workspace = true }

elf-config = { workspace = true }
