[package]
edition = "2024"
name    = "elf-storage"
version = "0.2.0"

[dependencies]
qdrant-client = { workspace = true }
serde_json    = { workspace = true }
sqlx          = { workspace = true }
thiserror     = { workspace = true }
time          = { workspace = true }
uuid          = { workspace = true }

elf-config = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

elf-testkit = { workspace = true }
