[package]
build   = "../../build.rs"
edition = "2024"
name    = "elf-api"
version = "0.1.0"

[dependencies]
axum               = { workspace = true }
clap               = { workspace = true }
color-eyre         = { workspace = true }
elf-cli            = { path = "../../crates/elf-cli" }
elf-config         = { path = "../../crates/elf-config" }
elf-service        = { path = "../../crates/elf-service" }
elf-storage        = { path = "../../crates/elf-storage" }
serde              = { workspace = true }
serde_json         = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
vergen-gitcl = { workspace = true }

[dev-dependencies]
sqlx  = { workspace = true }
tower = { version = "0.5" }
