[package]
edition = "2024"
name    = "elf-domain"
version = "0.1.0"

[dependencies]
elf-config = { path = "../elf-config" }
regex      = { version = "1.0" }
serde_json = { workspace = true }
time       = { workspace = true }
