[package]
edition = "2024"
name    = "elf-providers"
version = "0.1.0"

[dependencies]
blake3     = { workspace = true }
reqwest    = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }
tokio      = { workspace = true }

elf-config = { workspace = true }
